### ISSUE TITLE
How can I generate the cp.bin、sm.bin、wr.bin

### ISSUE THREAD

**Issue by pincution** [TeluguOCR/banti_segmenter#3]
I am new in the OCR. How can I generate the cp.bin、sm.bin、wr.bin, I cann't find it in the repository.

**Comment by rakeshvar** [comment]
Try Banti OCR. Antanci  is an old system that is not that good.

**Comment by pincution** [comment]
I just want a simple and effective OCR program, and put it into the DSP chip. OpenCV and tesseract seems to big. I hope you can give some suggestions to me.
